version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopassword
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      DATABASE_URI: postgresql://geouser:geopassword@db/analytics
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  db-data: